name: Deploy To Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.BASTION_IP }} >> ~/.ssh/known_hosts
      
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      
      - name: Create ansible.cfg مع bastion settings
        run: |
          cat > ansible/ansible.cfg << EOF
          [defaults]
          inventory = hosts.ini
          host_key_checking = False
          remote_user = ubuntu
          private_key_file = ~/.ssh/id_rsa
          timeout = 30
          
          [ssh_connection]
          ssh_args = -o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${{ secrets.BASTION_IP }}
          EOF
      
      - name: Run Ansible playbook
        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          cd ansible
          ansible-playbook -i hosts.ini deploy.yml \
          -e "aws_region=$AWS_REGION" \
          -e "aws_account_id=$AWS_ACCOUNT_ID" \
          -e "image_tag=latest"
